### ISSUE TITLE
Why extension name can not contains number digits?

### ISSUE THREAD

**Issue by chekun** [tjx666/setup-boilerplate#1]
Hello, I just downloaded your template. After running npx setup-boilerplate, I entered the name i18n-tools, but it kept prompting me that it must be in kebab-case, even though the format clearly meets the kebab-case requirement.

So I found the code here: https://github.com/tjx666/setup-boilerplate/blob/0edca2b7f76c40fd9e803eb0980769881e9bfa05/src/setups/vscode.ts#L37, and I noticed that the regex only allows lowercase letters and hyphens. Can you please explain why it can't include numbers?

**Comment by tjx666** [comment]
check latest v0.0.4 version, please.
